#!/bin/bash
sudo chmod +x main halt remove
echo "[Permissions updated]"
sudo cp ~/.bashrc /home/$(whoami)/.startupinfo/bashrc-backup
echo "[~/.bashrc backup written]"
cat <<EOF | sudo tee /home/$(whoami)/.startupinfo/startupinfocommand >/dev/null
#!/bin/bash
case "\$1" in
  -r) read -p "Are you sure (y/n): " conf; [ "\$conf" == "y" ] && cd \$(sudo find /home -type d -name ".startupinfo" -print -quit) && ./remove ;;
  -d) cd \$(sudo find /home -type d -name ".startupinfo" -print -quit) && ./halt ;;
  -h) echo -e "startupinfo [OPTIONS]\n  -h; help\n  -e; enable\n  -d; disable\n  -r; remove\n  -u; update\n  -v; version\n  -b; backup" ;;
  -e) cd \$(sudo find /home -type d -name ".startupinfo" -print -quit) && ./main ;;
  -u) cd \$(sudo find /home -type d -name ".startupinfo" -print -quit) && ./remove && cd /home/$(whoami) && git clone https://github.com/iloveblocks1234/.startupinfo.git && cd .startupinfo && sudo chmod +x setup && ./setup ;;
  -v) echo -e "Versions:\n  Version 1.0; Just the plain command\n  Version 1.1; Added a remove function and a README\n  Version 1.2; Added the command and fixed minor bugs\n  ___________________________________________________\n  Dev version 1.3; Improved safety features" ;;
  -b) sudo cp /home/$(whoami)/.startupinfo/bashrc-backup ~/.bashrc && echo "[Restoration complete]" ;;
esac
EOF
echo "[Command file written]"
sudo cp /home/$(whoami)/.startupinfo/startupinfocommand /bin/startupinfo /usr/bin/startupinfo
echo "[Command copied to /bin and /usr/bin]"
sudo chmod +x /bin/startupinfo /usr/bin/startupinfo
echo "[Command permissions updated]"
sudo rm -rf /home/$(whoami)/.startupinfo/startupinfocommand
echo "[Removed init files]"
echo "'startupinfo -h' for help"
